wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1679856552.225508
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
amsgrad:
  desc: null
  value: true
backbone:
  desc: null
  value: efficientnet_b2
batch_size:
  desc: null
  value: 8
dataset_split:
  desc: null
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  desc: null
  value: Vegetation Indexes
epochs:
  desc: null
  value: 60
freezing:
  desc: null
  value: 0.25
image_size:
  desc: null
  value:
  - 99
  - 80
lr:
  desc: null
  value: 0.004811985400546883
mAP_type:
  desc: null
  value: bbox
optimizer:
  desc: null
  value: AdamW
pansharpening:
  desc: null
  value: Simple Mean
scheduler:
  desc: null
  value: ReduceLROnPlateau
threshold:
  desc: null
  value: 0.005
weight_decay:
  desc: null
  value: 0.05673352338583247
