wandb_version: 1

amsgrad:
  value: true
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 60
freezing:
  value: 0.75
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.004953107422579677
mAP_type:
  value: bbox
optimizer:
  value: AdamW
pansharpening:
  value: Simple Mean
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.008962191075200954
