wandb_version: 1

amsgrad:
  value: false
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 60
freezing:
  value: 0.25
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.009380142723305968
mAP_type:
  value: bbox
optimizer:
  value: AdamW
pansharpening:
  value: Simple Mean
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.07601461062762044
