wandb_version: 1

amsgrad:
  value: true
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.4445941359151008
box_fg_iou_thresh:
  value: 0.6334640794365194
box_score_thresh:
  value: 0.8272032571334513
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.75
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.008288265370938575
mAP_type:
  value: bbox
optimizer:
  value: SGD
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.26367582780304255
rpn_fg_iou_thresh:
  value: 0.5411832240504022
rpn_score_thresh:
  value: 0.9412173658695702
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.05242758487908689
