wandb_version: 1

amsgrad:
  value: false
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.4658603658215485
box_fg_iou_thresh:
  value: 0.7483352134209229
box_score_thresh:
  value: 0.40509868039539776
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.75
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.0016212612891402477
mAP_type:
  value: bbox
optimizer:
  value: Adam
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.21246890283803835
rpn_fg_iou_thresh:
  value: 0.7120790251864133
rpn_score_thresh:
  value: 0.6238024798696001
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.21585223615425947
