wandb_version: 1

amsgrad:
  value: false
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.23197454337480564
box_fg_iou_thresh:
  value: 0.729570252143725
box_score_thresh:
  value: 0.6749868620198274
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.25
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.008234843603089017
mAP_type:
  value: bbox
optimizer:
  value: SGD
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.1760832743037533
rpn_fg_iou_thresh:
  value: 0.7781443091281853
rpn_score_thresh:
  value: 0.5712710472499138
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.5144106633049924
