wandb_version: 1

amsgrad:
  value: true
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.12693211289971862
box_fg_iou_thresh:
  value: 0.6364678927700289
box_score_thresh:
  value: 0.2650375424881818
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.5
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.0021976082294604573
mAP_type:
  value: bbox
optimizer:
  value: Adadelta
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.30549998951381796
rpn_fg_iou_thresh:
  value: 0.6086263788476247
rpn_score_thresh:
  value: 0.8406409812881166
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.82418349559931
