wandb_version: 1

amsgrad:
  value: false
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.4916841292241466
box_fg_iou_thresh:
  value: 0.7955851119264221
box_score_thresh:
  value: 0.4276197893254151
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.5
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.004416276711202483
mAP_type:
  value: bbox
optimizer:
  value: Adam
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.2952418361482443
rpn_fg_iou_thresh:
  value: 0.6133251120698558
rpn_score_thresh:
  value: 0.5422075993648131
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.9851898561048252
