wandb_version: 1

amsgrad:
  value: true
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.384795195664695
box_fg_iou_thresh:
  value: 0.6751876973399064
box_score_thresh:
  value: 0.3464424011231115
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.75
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.006381746764638178
mAP_type:
  value: bbox
optimizer:
  value: Adam
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.23292491528273
rpn_fg_iou_thresh:
  value: 0.6447740441104642
rpn_score_thresh:
  value: 0.9403194361991952
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.014957877723280949
