wandb_version: 1

amsgrad:
  value: true
backbone:
  value: efficientnet_b0
batch_size:
  value: 8
box_bg_iou_thresh:
  value: 0.3924268940793645
box_fg_iou_thresh:
  value: 0.8411928259800787
box_score_thresh:
  value: 0.335167657116392
dataset_split:
  value:
  - 0.8
  - 0.2
dimensionality_reduction:
  value: Vegetation Indexes
epochs:
  value: 100
freezing:
  value: 0.75
image_size:
  value:
  - 99
  - 80
lr:
  value: 0.002209370905175976
mAP_type:
  value: bbox
optimizer:
  value: SGD
pansharpening:
  value: Simple Mean
rpn_bg_iou_thresh:
  value: 0.2459951456395659
rpn_fg_iou_thresh:
  value: 0.5580568872354977
rpn_score_thresh:
  value: 0.6853653674303624
scheduler:
  value: ReduceLROnPlateau
threshold:
  value: 0.005
weight_decay:
  value: 0.7298041502369346
